const CargoActions = {
  GET_ALL_CARGOES: {
    REQUESTING: 'GET_ALL_CARGOES_REQUESTING',
    SUCCESS: 'GET_ALL_CARGOES_SUCCESS',
    ERROR: 'GET_ALL_CARGOES_ERROR',
  },
  GET_ALL_CARGOES_STATES: {
    REQUESTING: 'GET_ALL_CARGOES_STATES_REQUESTING',
    SUCCESS: 'GET_ALL_CARGOES_STATES_SUCCESS',
    ERROR: 'GET_ALL_CARGOES_STATES_ERROR',
  },
  VERIFY_CARGO: {
    REQUESTING: 'VERIFY_CARGO_REQUESTING',
    SUCCESS: 'VERIFY_CARGO_SUCCESS',
    ERROR: 'VERIFY_CARGO_ERROR',
  },
  CHANGE_CARGO_STATE: {
    REQUESTING: 'CHANGE_CARGO_STATE_REQUESTING',
    SUCCESS: 'CHANGE_CARGO_STATE_SUCCESS',
    ERROR: 'CHANGE_CARGO_STATE_ERROR',
  },
  REJECT_CARGO: {
    REQUESTING: 'REJECT_CARGO_REQUESTING',
    SUCCESS: 'REJECT_CARGO_SUCCESS',
    ERROR: 'REJECT_CARGO_ERROR',
  },
  CHANGE_STATE_TO_SHIPPED: {
    REQUESTING: 'CHANGE_STATE_TO_SHIPPED_REQUESTING',
    SUCCESS: 'CHANGE_STATE_TO_SHIPPED_SUCCESS',
    ERROR: 'CHANGE_STATE_TO_SHIPPED_ERROR',
  },
  CHANGE_STATE_TO_DELIVERED: {
    REQUESTING: 'CHANGE_STATE_TO_DELIVERED_REQUESTING',
    SUCCESS: 'CHANGE_STATE_TO_DELIVERED_SUCCESS',
    ERROR: 'CHANGE_STATE_TO_DELIVERED_ERROR',
  },
  VERIFY_MODAL_STATUS: 'VERIFY_MODAL_STATUS',
  REJECT_MODAL_STATUS: 'REJECT_MODAL_STATUS',
  USER_CARGOES_MODAL_STATE: 'USER_CARGOES_MODAL_STATE',
  SHOW_CARGO_MODAL_STATE: 'SHOW_CARGO_MODAL_STATE',
  GET_USER_CARGOES: {
    REQUESTING: 'GET_USER_CARGOES_REQUESTING',
    SUCCESS: 'GET_USER_CARGOES_SUCCESS',
    ERROR: 'GET_USER_CARGOES_ERROR',
  },
};
export default CargoActions;
