class CargoActions {
  static GET_ALL_CARGOES = {
    REQUESTING: 'GET_ALL_CARGOES_REQUESTING',
    SUCCESS: 'GET_ALL_CARGOES_SUCCESS',
    ERROR: 'GET_ALL_CARGOES_ERROR',
  };
  static VERIFY_CARGO = {
    REQUESTING: 'VERIFY_CARGO_REQUESTING',
    SUCCESS: 'VERIFY_CARGO_SUCCESS',
    ERROR: 'VERIFY_CARGO_ERROR',
  };
  static REJECT_CARGO = {
    REQUESTING: 'REJECT_CARGO_REQUESTING',
    SUCCESS: 'REJECT_CARGO_SUCCESS',
    ERROR: 'REJECT_CARGO_ERROR',
  };
  static VERIFY_MODAL_STATUS = 'VERIFY_MODAL_STATUS';
  static REJECT_MODAL_STATUS = 'REJECT_MODAL_STATUS';
}
export default CargoActions;
