class CargoActions {
  static GET_ALL_CARGOES = {
    REQUESTING: 'GET_ALL_CARGOES_REQUESTING',
    SUCCESS: 'GET_ALL_CARGOES_SUCCESS',
    ERROR: 'GET_ALL_CARGOES_ERROR',
  };
  static GET_ALL_CARGOES_STATES = {
    REQUESTING: 'GET_ALL_CARGOES_STATES_REQUESTING',
    SUCCESS: 'GET_ALL_CARGOES_STATES_SUCCESS',
    ERROR: 'GET_ALL_CARGOES_STATES_ERROR',
  };
  static VERIFY_CARGO = {
    REQUESTING: 'VERIFY_CARGO_REQUESTING',
    SUCCESS: 'VERIFY_CARGO_SUCCESS',
    ERROR: 'VERIFY_CARGO_ERROR',
  };
  static CHANGE_CARGO_STATE = {
    REQUESTING: 'CHANGE_CARGO_STATE_REQUESTING',
    SUCCESS: 'CHANGE_CARGO_STATE_SUCCESS',
    ERROR: 'CHANGE_CARGO_STATE_ERROR',
  };
  static REJECT_CARGO = {
    REQUESTING: 'REJECT_CARGO_REQUESTING',
    SUCCESS: 'REJECT_CARGO_SUCCESS',
    ERROR: 'REJECT_CARGO_ERROR',
  };
  static CHANGE_STATE_TO_SHIPPED = {
    REQUESTING: 'CHANGE_STATE_TO_SHIPPED_REQUESTING',
    SUCCESS: 'CHANGE_STATE_TO_SHIPPED_SUCCESS',
    ERROR: 'CHANGE_STATE_TO_SHIPPED_ERROR',
  };
  static CHANGE_STATE_TO_DELIVERED = {
    REQUESTING: 'CHANGE_STATE_TO_DELIVERED_REQUESTING',
    SUCCESS: 'CHANGE_STATE_TO_DELIVERED_SUCCESS',
    ERROR: 'CHANGE_STATE_TO_DELIVERED_ERROR',
  };
  static VERIFY_MODAL_STATUS = 'VERIFY_MODAL_STATUS';
  static REJECT_MODAL_STATUS = 'REJECT_MODAL_STATUS';
  static CHANGE_CARGO_STATE = {
    REQUESTING: 'CHANGE_CARGO_STATE_REQUESTING',
    SUCCESS: 'CHANGE_CARGO_STATE_SUCCESS',
    ERROR: 'CHANGE_CARGO_STATE_ERROR',
  };
}
export default CargoActions;
