class CountryActions {
  static GET_ALL_COUNTRIES = {
    REQUESTING: 'GET_ALL_COUNTRIES_REQUESTING',
    SUCCESS: 'GET_ALL_COUNTRIES_SUCCESS',
    ERROR: 'GET_ALL_COUNTRIES_ERROR',
  };
  static CREATE_COUNTRY = {
    REQUESTING: 'CREATE_COUNTRY_REQUESTING',
    SUCCESS: 'CREATE_COUNTRY_SUCCESS',
    ERROR: 'CREATE_COUNTRY_ERROR',
  };
  static DELETE_COUNTRY = {
    REQUESTING: 'DELETE_COUNTRY_REQUESTING',
    SUCCESS: 'DELETE_COUNTRY_SUCCESS',
    ERROR: 'DELETE_COUNTRY_ERROR',
  };
}

export default CountryActions;
