class DirectionActions {
  static GET_ALL_DIRECTIONS = {
    REQUESTING: 'GET_ALL_DIRECTIONS_REQUESTING',
    SUCCESS: 'GET_ALL_DIRECTIONS_SUCCESS',
    ERROR: 'GET_ALL_DIRECTIONS_ERROR',
  };
  static CREATE_DIRECTION = {
    REQUESTING: 'CREATE_DIRECTION_REQUESTING',
    SUCCESS: 'CREATE_DIRECTION_SUCCESS',
    ERROR: 'CREATE_DIRECTION_ERROR',
  };
  static DELETE_DIRECTION = {
    REQUESTING: 'DELETE_DIRECTION_REQUESTING',
    SUCCESS: 'DELETE_DIRECTION_SUCCESS',
    ERROR: 'DELETE_DIRECTION_ERROR',
  };
}

export default DirectionActions;
