const DirectionActions = {
  GET_ALL_DIRECTIONS: {
    REQUESTING: 'DIRECTION_GET_ALL_DIRECTIONS_REQUESTING',
    SUCCESS: 'DIRECTION_GET_ALL_DIRECTIONS_SUCCESS',
    ERROR: 'DIRECTION_GET_ALL_DIRECTIONS_ERROR',
  },
  CREATE_DIRECTION: {
    REQUESTING: 'DIRECTION_CREATE_DIRECTION_REQUESTING',
    SUCCESS: 'DIRECTION_CREATE_DIRECTION_SUCCESS',
    ERROR: 'DIRECTION_CREATE_DIRECTION_ERROR',
  },
  DELETE_DIRECTION: {
    REQUESTING: 'DIRECTION_DELETE_DIRECTION_REQUESTING',
    SUCCESS: 'DIRECTION_DELETE_DIRECTION_SUCCESS',
    ERROR: 'DIRECTION_DELETE_DIRECTION_ERROR',
  },
  CHANGE_STATE: {
    REQUESTING: 'DIRECTION_CHANGE_STATE_REQUESTING',
    SUCCESS: 'DIRECTION_CHANGE_STATE_SUCCESS',
    ERROR: 'DIRECTION_CHANGE_STATE_ERROR',
  },
};

export default DirectionActions;
