const UserTypes = {
  GET_USERS: {
    REQUESTING: 'USER_TYPES_GET_USERS_REQUESTING',
    SUCCESS: 'USER_TYPES_GET_USERS_SUCCESS',
    ERROR: 'USER_TYPES_GET_USERS_ERROR',
  },
  CHANGE_USER_STATE: {
    REQUESTING: 'USER_TYPES_CHANGE_USER_STATE_REQUESTING',
    SUCCESS: 'USER_TYPES_CHANGE_USER_STATE_SUCCESS',
    ERROR: 'USER_TYPES_CHANGE_USER_STATE_ERROR',
  },
  CHANGE_ROLE: {
    REQUESTING: 'USER_TYPES_CHANGE_ROLE_REQUESTING',
    SUCCESS: 'USER_TYPES_CHANGE_ROLE_SUCCESS',
    ERROR: 'USER_TYPES_CHANGE_ROLE_ERROR',
  },
};

export default UserTypes;
